version: '3.7'
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test123
    ports:
      - "5432:5432"
    volumes:
      - ./.db:/var/lib/postgresql/data
  front:
    image: httpd:latest
    ports:
      - "3001:80"
    volumes:
      - ./front:/usr/local/apache2/htdocs